name: Infra_Deployment_Modules

on:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format check
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        continue-on-error: true
        run: |
          tflint --init
          tflint
     
      # - name: Terraform Security Scan
      #   uses: bridgecrewio/checkov-action@v12
      #   with:
      #     directory: .

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Upload Plan Artifact
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan 

  Terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform_plan
    environment: Dev   # 👈 approval required

    steps:
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Download Plan Artifact
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      # Terraform Apply using saved plan
      - name: Terraform Apply
        run: terraform apply tfplan
      
